env:
  es2020: true
parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
    'no-empty-function': 'off'
    '@typescript-eslint/no-empty-function': 'off'
    '@typescript-eslint/no-explicit-any': 'off'
